// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: protos/parser_service.proto

package parser_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PostParserServiceClient is the client API for PostParserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostParserServiceClient interface {
	ParseData(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ParseDataResponse, error)
}

type postParserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostParserServiceClient(cc grpc.ClientConnInterface) PostParserServiceClient {
	return &postParserServiceClient{cc}
}

func (c *postParserServiceClient) ParseData(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ParseDataResponse, error) {
	out := new(ParseDataResponse)
	err := c.cc.Invoke(ctx, "/pb.PostParserService/ParseData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostParserServiceServer is the server API for PostParserService service.
// All implementations must embed UnimplementedPostParserServiceServer
// for forward compatibility
type PostParserServiceServer interface {
	ParseData(context.Context, *Empty) (*ParseDataResponse, error)
	mustEmbedUnimplementedPostParserServiceServer()
}

// UnimplementedPostParserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPostParserServiceServer struct {
}

func (UnimplementedPostParserServiceServer) ParseData(context.Context, *Empty) (*ParseDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseData not implemented")
}
func (UnimplementedPostParserServiceServer) mustEmbedUnimplementedPostParserServiceServer() {}

// UnsafePostParserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostParserServiceServer will
// result in compilation errors.
type UnsafePostParserServiceServer interface {
	mustEmbedUnimplementedPostParserServiceServer()
}

func RegisterPostParserServiceServer(s grpc.ServiceRegistrar, srv PostParserServiceServer) {
	s.RegisterService(&PostParserService_ServiceDesc, srv)
}

func _PostParserService_ParseData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostParserServiceServer).ParseData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostParserService/ParseData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostParserServiceServer).ParseData(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PostParserService_ServiceDesc is the grpc.ServiceDesc for PostParserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostParserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PostParserService",
	HandlerType: (*PostParserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseData",
			Handler:    _PostParserService_ParseData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/parser_service.proto",
}
